language: python
cache: pip

services:
  - postgresql

python:
  - "3.6"
  - "3.7"
  - "3.8"

env:
  global:
    - PGUSER=postgres
    - PGDATABASE=postgres
    - PGPASSWORD=
  matrix:
    - DJANGO=2.1
    - DJANGO=2.2
    - DJANGO=3.0

matrix:
  fast_finish: true
  include:
    - { python: "3.7", env: TOXENV=isort }
    - { python: "3.7", env: TOXENV=black }
    # - { python: "3.7", env: TOXENV=docs }

install:
  - pip install tox-travis

script:
  - tox

after_success:
  - pip install codecov
  - codecov -e TOXENV,DJANGO

notifications:
  email: false
