# Generated by Django 2.2.10 on 2020-03-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_auth_adfs_db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adfsconfig",
            name="sync_groups",
            field=models.BooleanField(
                default=True,
                help_text="Synchronize the local user groups with the ADFS groups. Note that this means a user is removed from all groups if there is no group claim. Uncheck to manage groups manually.",
                verbose_name="synchronize groups?",
            ),
        ),
    ]
