# Generated by Django 2.2.14 on 2021-03-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_auth_adfs_db", "0002_adfsconfig_sync_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="adfsconfig",
            name="client_secret",
            field=models.CharField(
                blank=True,
                help_text="This is a client secret created for the Azure AD application.",
                max_length=200,
                verbose_name="client secret",
            ),
        ),
        migrations.AlterField(
            model_name="adfsconfig",
            name="client_id",
            field=models.CharField(
                blank=True,
                help_text="This is the Azure 'Client ID' or the on-premise 'Client Identifier' value.",
                max_length=50,
                verbose_name="client ID",
            ),
        ),
        migrations.AlterField(
            model_name="adfsconfig",
            name="relying_party_id",
            field=models.CharField(
                help_text="For Azure AD, this is the client ID, for on-premise this is the identifier of the web application.",
                max_length=255,
                verbose_name="relying party ID",
            ),
        ),
        migrations.AlterField(
            model_name="adfsconfig",
            name="tenant_id",
            field=models.CharField(
                blank=True,
                help_text="Your Azure tenant ID, you can find this on the overview page.",
                max_length=50,
                verbose_name="Azure Tenant ID",
            ),
        ),
    ]
